name: youchat
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  firebase_storage: ^11.2.7
  emoji_picker_flutter: ^1.6.1
  firebase_messaging: ^14.6.8
  http: ^0.13.6
  flutter_notification_channel: ^2.0.0
  gallery_saver: ^2.1.1
  provider: ^6.0.5
  gap: ^3.0.1
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
  
  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
